# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: (untitled)
email: rahulan [dot] c [at] gmail [dot] com
description: > # this means to ignore newlines until "baseurl:"
  A home for nascent projects
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://rchandra1.github,io" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  rchandra1

# Build settings
markdown: kramdown
